filter:
  paths: [src/*]
checks:
  php:
    code_rating: true
    duplication: true
tools:
  external_code_coverage:
    runs: 2
  php_code_sniffer:
    config:
      standard: "PSR2"
build:
  nodes:
    analysis:
      tests:
        override:
          - phpcs-run --standard=PSR2
          - php-scrutinizer-run