filter:
  paths: [src/*, tests/*]
checks:
  php: true
tools:
  external_code_coverage:
    runs: 2
  php_code_sniffer:
    config:
      standard: "PSR2"
build:
  nodes:
    analysis:
      tests:
        override:
          - phpcs-run
          - php-scrutinizer-run